export const Period = "Period"

// Income Statement
export const Revenue = "Revenue"
export const CostOfGoodsSold = "CostOfGoodsSold"
export const GrossProfit = "GrossProfit"
export const OperatingIncome = "OperatingIncome"
export const OperatingExpense = "OperatingExpense"
export const NonOperatingExpense = "NonOperatingExpense"
export const TaxExpense = "TaxExpense"
export const PretaxIncome = "PretaxIncome"
export const InterestExpense = "InterestExpense"
export const NetIncome = "NetIncome"

// Balance Sheet
export const CurrentAsset = "CurrentAsset"
export const PropertyPlanetAndEquipement = "PropertyPlanetAndEquipement"
export const LongTermAsset = "LongTermAsset"
export const TotalAsset = "TotalAsset"
export const CurrentLiability = "CurrentLiability"
export const LongTermDebt = "LongTermLiability"
export const LongTermLiability = "LongTermLiability"
export const TotalLiability = "TotalLiability"
export const ShareholdersEquity = "ShareholdersEquity"

// Non-GaaP / Other
export const FreeCashFlow = "FreeCashFlow"
export const FreeCashFlowPerShare = "FreeCashFlowPerShare"
export const CapitalExpenditure = "CapitalExpenditure"
export const DepreciationAmortization = "DepreciationAmortization"
export const StockBasedCompensation = "StockBasedCompensation"
export const ChangeInWorkingCapital = "ChangeInWorkingCapital"
export const SharesOutstanding = "SharesOutstanding"
export const DilutedSharesOutstanding = "DilutedSharesOutstanding"
export const DiscountFactor = "DiscountFactor"
export const TerminalValuePerShare = "TerminalValuePerShare"
export const PresentValueOfEarningsPerShare = "PresentValueOfEarningsPerShare"
export const PresentValueOfTerminalValuePerShare = "PresentValueOfTerminalValuePerShare"
export const PresentValuePerShare = "PresentValuePerShare"
export const EarningsPerShare = "EarningsPerShare"

export const IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest =
    "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest"
export const AccountsPayableCurrent = "AccountsPayableCurrent"
export const AccountsReceivableNetCurrent = "AccountsReceivableNetCurrent"
export const AccruedLiabilitiesandOtherLiabilitiesCurrent = "AccruedLiabilitiesandOtherLiabilitiesCurrent"
export const AccumulatedOtherComprehensiveIncomeLossNetOfTax = "AccumulatedOtherComprehensiveIncomeLossNetOfTax"
export const AdditionalPaidInCapital = "AdditionalPaidInCapital"
export const AssetImpairmentCharges = "AssetImpairmentCharges"
export const AvailableForSaleSecuritiesDebtSecuritiesCurrent = "AvailableForSaleSecuritiesDebtSecuritiesCurrent"
export const CapitalizedContractCostAmortization = "CapitalizedContractCostAmortization"
export const CashAndCashEquivalentsAtCarryingValue = "CashAndCashEquivalentsAtCarryingValue"
export const CommitmentsAndContingencies = "CommitmentsAndContingencies"
export const CommonStockValue = "CommonStockValue"
export const ContractWithCustomerLiabilityCurrent = "ContractWithCustomerLiabilityCurrent"
export const CostOfGoodsAndServicesSold = "CostOfGoodsAndServicesSold"
export const DeprecationDepletionAndAmortizationExcludingAmortizationOfDeferredSalesCommissions =
    "DeprecationDepletionAndAmortizationExcludingAmortizationOfDeferredSalesCommissions"
export const EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents =
    "EffectOfExchangeRateOnCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents"
export const EmployeeRelatedLiabilitiesCurrent = "EmployeeRelatedLiabilitiesCurrent"
export const EquitySecuritiesFvNiGainLoss = "EquitySecuritiesFvNiGainLoss"
export const FinanceLeaseLiabilityCurrent = "FinanceLeaseLiabilityCurrent"
export const FinanceLeaseLiabilityNoncurrent = "FinanceLeaseLiabilityNoncurrent"
export const FinanceLeasePrincipalPayments = "FinanceLeasePrincipalPayments"
export const GeneralAndAdministrativeExpense = "GeneralAndAdministrativeExpense"
export const Goodwill = "Goodwill"
export const IncomeTaxExpenseBenefit = "IncomeTaxExpenseBenefit"
export const IncreaseDecreaseInAccountsAndOtherReceivables = "IncreaseDecreaseInAccountsAndOtherReceivables"
export const IncreaseDecreaseInAccountsPayable = "IncreaseDecreaseInAccountsPayable"
export const IncreaseDecreaseInAccruedLiabilitiesAndOtherLiabilities =
    "IncreaseDecreaseInAccruedLiabilitiesAndOtherLiabilities"
export const IncreaseDecreaseInContractWithCustomerLiability = "IncreaseDecreaseInContractWithCustomerLiability"
export const IncreaseDecreaseInEmployeeRelatedLiabilities = "IncreaseDecreaseInEmployeeRelatedLiabilities"
export const IncreaseDecreaseInOtherNoncurrentLiabilities = "IncreaseDecreaseInOtherNoncurrentLiabilities"
export const IncreaseDecreaseInOtherOperatingAssets = "IncreaseDecreaseInOtherOperatingAssets"
export const IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets =
    "IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets"
export const IncreaseDecreaseTenantImprovementAllowanceReimbursement =
    "IncreaseDecreaseTenantImprovementAllowanceReimbursement"
export const IntangibleAssetsNetExcludingGoodwill = "IntangibleAssetsNetExcludingGoodwill"
export const InterestIncomeExpenseNonoperatingNet = "InterestIncomeExpenseNonoperatingNet"
export const OperatingLeaseLiabilityCurrent = "OperatingLeaseLiabilityCurrent"
export const OperatingLeaseLiabilityNoncurrent = "OperatingLeaseLiabilityNoncurrent"
export const OperatingLeaseRightOfUseAsset = "OperatingLeaseRightOfUseAsset"
export const OtherAssetsNoncurrent = "OtherAssetsNoncurrent"
export const OtherLiabilitiesNoncurrent = "OtherLiabilitiesNoncurrent"
export const OtherNoncashIncomeExpense = "OtherNoncashIncomeExpense"
export const OtherNonoperatingIncomeExpense = "OtherNonoperatingIncomeExpense"
export const PaymentsForProceedsFromOtherInvestingActivities = "PaymentsForProceedsFromOtherInvestingActivities"
export const PaymentsForRepurchaseOfCommonStock = "PaymentsForRepurchaseOfCommonStock"
export const PaymentsOfStockIssuanceCosts = "PaymentsOfStockIssuanceCosts"
export const PaymentsRelatedToTaxWithholdingForShareBasedCompensation =
    "PaymentsRelatedToTaxWithholdingForShareBasedCompensation"
export const PaymentsToAcquireAvailableForSaleSecuritiesDebt = "PaymentsToAcquireAvailableForSaleSecuritiesDebt"
export const PaymentsToAcquireBusinessesNetOfCashAcquired = "PaymentsToAcquireBusinessesNetOfCashAcquired"
export const PaymentsToAcquireIntangibleAssets = "PaymentsToAcquireIntangibleAssets"
export const PaymentsToAcquirePropertyPlantAndEquipment = "PaymentsToAcquirePropertyPlantAndEquipment"
export const PreferredStockValue = "PreferredStockValue"
export const PrepaidExpenseAndOtherAssetsCurrent = "PrepaidExpenseAndOtherAssetsCurrent"
export const ProceedsFromIssuanceInitialPublicOffering = "ProceedsFromIssuanceInitialPublicOffering"
export const ProceedsFromIssuanceOfCommonStock = "ProceedsFromIssuanceOfCommonStock"
export const ProceedsFromMaturitiesPrepaymentsAndCallsOfShorttermInvestments =
    "ProceedsFromMaturitiesPrepaymentsAndCallsOfShorttermInvestments"
export const ProceedsFromPaymentsForOtherFinancingActivities = "ProceedsFromPaymentsForOtherFinancingActivities"
export const ProceedsFromSaleOfShortTermInvestments = "ProceedsFromSaleOfShortTermInvestments"
export const PropertyPlantAndEquipmentNet = "PropertyPlantAndEquipmentNet"
export const ResearchAndDevelopmentExpense = "ResearchAndDevelopmentExpense"
export const RetainedEarningsAccumulatedDeficit = "RetainedEarningsAccumulatedDeficit"
export const RevenueFromContractWithCustomerExcludingAssessedTax =
    "RevenueFromContractWithCustomerExcludingAssessedTax"
export const SellingAndMarketingExpense = "SellingAndMarketingExpense"
export const ShareBasedCompensation = "ShareBasedCompensation"

export const EarningsPerShareDiluted = "EarningsPerShareDiluted"
export const EarningsPerShareBasic = "EarningsPerShareBasic"
export const WeightedAverageNumberOfDilutedSharesOutstanding = "WeightedAverageNumberOfDilutedSharesOutstanding"
export const WeightedAverageNumberOfSharesOutstandingBasic = "WeightedAverageNumberOfSharesOutstandingBasic"
export const NetIncomeLoss = "NetIncomeLoss"
export const CostsAndExpenses = "CostsAndExpenses"